---
- connection: local
  hosts: localhost
  vars:
    user: alex
  tasks:

  # dotfiles and static files
  ###########################
  - name: copy home directory
    copy:
      src: home/
      dest: ~/
  - name: chmod home/bin scripts
    file:
      path: "{{ item }}"
      mode: 0755
    with_fileglob:
      - ~/bin/*

  # apt packages
  ##############
  - name: install apt packages
    become: yes
    apt:
      update_cache: yes
      state: latest
      name:
      # programs
      - ack-grep
      - audacity
      - curl
      - chromium-browser
      - ffmpeg
      - fish
      - gimp
      - git
      - gnome-disk-utility
      - handbrake
      - htop
      - imagemagick
      - libimage-exiftool-perl
      - libreoffice
      - nautilus-dropbox
      - pavucontrol
      - python-pip
      - shutter
      - silversearcher-ag
      - sound-juicer
      - texlive
      - texmaker
      - transmission
      - vlc
      - wget
      - xournal
      # libraries / dependencies
      - build-essential
      - ruby-dev
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev

  # pip packages
  ##############
  - name: pip packages
    become: yes
    pip:
      name:
      - eyeD3
      - youtube-dl

  # install n (node version management)
  #########################
  - name: download n (node version manager)
    git:
      repo: https://github.com/tj/n.git
      dest: ~/.n

  # make fish default shell
  #########################
  - name: make fish default shell
    become: yes
    user:
      name: "{{ user }}"
      shell: /usr/bin/fish
