---
- connection: local
  hosts: localhost
  vars:
    user: alex
  tasks:

  # dotfiles and static files
  ###########################
  - name: copy home directory
    copy:
      src: home/
      dest: ~/
  - name: chmod home/bin scripts
    file:
      path: "{{ item }}"
      mode: 0755
    with_fileglob:
      - ~/bin/*

  # apt packages
  ##############
  - name: install apt packages
    become: yes
    apt:
      update_cache: yes
      state: latest
      name:
      # programs
      - ack-grep
      - audacity
      - curl
      - elementary-xfce-icon-theme
      - eyed3
      - ffmpeg
      - file-roller
      - fish
      - fonts-powerline
      - gimp
      - git
      - gnome-disk-utility
      - greybird-gtk-theme
      - handbrake
      - htop
      - imagemagick
      - libimage-exiftool-perl
      - libreoffice
      - pavucontrol
      - python-pip
      - silversearcher-ag
      - software-properties-gtk
      - sound-juicer
      - transmission
      - vlc
      - wget
      - xournal

  # install n (node version management)
  #########################
  - name: download n (node version manager)
    git:
      repo: https://github.com/tj/n.git
      dest: ~/.n

  # make fish default shell
  #########################
  - name: make fish default shell
    become: yes
    user:
      name: "{{ user }}"
      shell: /usr/bin/fish
